version: 2.1

orbs:
  rn: react-native-community/react-native@dev:0.1.0-rc10

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  android_e2e:
    steps:
      - attach_workspace:
        at: .
      - rn/setup_macos_executor
      - rn/yarn_install
      - rn/android_emulator_start

      - run:
        name: Build and install android release apk
        command: cd example && npx react-native run-android --variant release
      - run:
        name: Run detox tests
        command: yarn test:e2e:android

  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run lint
      - run:
          name: Flow
          command: yarn run test:flow
      - run:
          name: TypeScript
          command: yarn run test:typescript
      - run:
          name: Build Android JavaScript Bundle
          command: yarn run bundle:e2e:android
      - run:
          name: Build iOS JavaScript Bundle
          command: yarn run bundle:e2e:ios
      - persist_to_workspace:
          root: .
          paths:
            - .tmp

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: debug
          requires:
            - analyse
      - rn/android_build:
          name: build_android_release
          project_path: "example/android"
          build_type: release
          requires:
            - analyse
      - android_e2e:
          requires:
            - analyse
      - rn/ios_build_and_test:
          project_path: "example/ios/StatusBarExample.xcodeproj"
          derived_data_path: "example/ios/build"
          device: "iPhone X"
          build_configuration: "Release"
          scheme: "StatusBarExample"
          detox_configuration: "ios.sim.release"
          requires:
            - analyse
